from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from backend.sales_workspace.schemas import SalesWorkspace, WorkspaceOperation, WorkspacePatch, utc_now


class RuntimeDraftModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class WorkspacePatchDraftOperation(RuntimeDraftModel):
    type: str
    payload: dict[str, Any] = Field(default_factory=dict)


class WorkspacePatchDraft(RuntimeDraftModel):
    id: str
    workspace_id: str
    base_workspace_version: int
    operations: list[WorkspacePatchDraftOperation]
    author: str = "runtime_patchdraft_prototype"
    instruction: str = ""
    runtime_metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("operations")
    @classmethod
    def operations_must_not_be_empty(
        cls,
        value: list[WorkspacePatchDraftOperation],
    ) -> list[WorkspacePatchDraftOperation]:
        if not value:
            raise ValueError("WorkspacePatchDraft.operations must not be empty")
        return value


def generate_deterministic_workspace_patch_draft(
    workspace: SalesWorkspace,
    *,
    base_workspace_version: int,
    instruction: str = "",
) -> WorkspacePatchDraft:
    next_version = workspace.workspace_version + 1
    round_id = "rr_runtime_001"
    source_id = "src_runtime_001"
    candidate_id = "cand_runtime_001"

    return WorkspacePatchDraft(
        id=f"draft_runtime_v{next_version}",
        workspace_id=workspace.id,
        base_workspace_version=base_workspace_version,
        instruction=instruction,
        runtime_metadata={
            "provider": "deterministic_runtime_patchdraft_prototype",
            "mode": "no_llm_no_langgraph",
            "kernel_boundary": (
                "Runtime returns WorkspacePatchDraft; Sales Workspace Kernel materializes, "
                "validates, and writes formal objects."
            ),
        },
        operations=[
            WorkspacePatchDraftOperation(
                type="upsert_research_round",
                payload={
                    "id": round_id,
                    "round_index": 3,
                    "objective": "Prototype runtime draft adds one source-backed candidate.",
                    "summary": "Deterministic runtime draft for workspace writeback boundary validation.",
                    "limitations": [
                        "Prototype-only deterministic payload.",
                        "No real LLM, search, contact discovery, or CRM enrichment.",
                    ],
                },
            ),
            WorkspacePatchDraftOperation(
                type="upsert_research_source",
                payload={
                    "id": source_id,
                    "round_id": round_id,
                    "title": "Runtime prototype fixture source",
                    "url": "https://example.com/runtime-prototype-source",
                    "source_type": "prototype_fixture",
                    "reliability": "high",
                    "excerpt": "Deterministic source-backed evidence for runtime patch draft boundary validation.",
                },
            ),
            WorkspacePatchDraftOperation(
                type="upsert_company_candidate",
                payload={
                    "id": candidate_id,
                    "name": "Runtime Draft Co",
                    "summary": "High-fit deterministic candidate generated by Runtime PatchDraft prototype.",
                    "industry": "manufacturing software",
                    "region": "China",
                    "company_size": "mid-market",
                    "status": "active",
                    "round_ids": [round_id],
                },
            ),
            WorkspacePatchDraftOperation(
                type="upsert_candidate_observation",
                payload={
                    "id": "obs_runtime_fit",
                    "candidate_id": candidate_id,
                    "source_id": source_id,
                    "round_id": round_id,
                    "signal_type": "fit",
                    "summary": "Runtime Draft Co matches the active manufacturing ERP direction.",
                    "polarity": "positive",
                    "strength": 5,
                },
            ),
            WorkspacePatchDraftOperation(
                type="upsert_candidate_observation",
                payload={
                    "id": "obs_runtime_pain",
                    "candidate_id": candidate_id,
                    "source_id": source_id,
                    "round_id": round_id,
                    "signal_type": "pain",
                    "summary": "The candidate shows strong pain around operations data fragmentation.",
                    "polarity": "positive",
                    "strength": 5,
                },
            ),
            WorkspacePatchDraftOperation(
                type="upsert_candidate_observation",
                payload={
                    "id": "obs_runtime_timing",
                    "candidate_id": candidate_id,
                    "source_id": source_id,
                    "round_id": round_id,
                    "signal_type": "timing",
                    "summary": "The candidate is actively evaluating workflow automation.",
                    "polarity": "positive",
                    "strength": 5,
                },
            ),
            WorkspacePatchDraftOperation(
                type="upsert_candidate_observation",
                payload={
                    "id": "obs_runtime_source_quality",
                    "candidate_id": candidate_id,
                    "source_id": source_id,
                    "round_id": round_id,
                    "signal_type": "source_quality",
                    "summary": "The prototype source is marked high reliability for deterministic validation.",
                    "polarity": "positive",
                    "strength": 5,
                },
            ),
        ],
    )


def materialize_workspace_patch(draft: WorkspacePatchDraft) -> WorkspacePatch:
    return WorkspacePatch(
        id=draft.id.replace("draft_", "patch_", 1),
        workspace_id=draft.workspace_id,
        base_workspace_version=draft.base_workspace_version,
        operations=[
            WorkspaceOperation(type=operation.type, payload=operation.payload)
            for operation in draft.operations
        ],
        author=draft.author,
        message=f"Runtime PatchDraft prototype: {draft.instruction}".strip(),
        created_at=utc_now(),
    )
